"""
output/formatter.py
Formats documentation into Markdown, HTML, or JSON output.
"""

import json
import re
import html as html_module
from datetime import datetime
from typing import Dict, Optional


# ---------------------------------------------------------------------------
# Markdown output
# ---------------------------------------------------------------------------

def format_markdown(sections: Dict[str, str], analysis: Dict) -> str:
    """Assemble all sections into a single Markdown document."""
    project_name = analysis.get("project_name", "Project Documentation")
    timestamp = datetime.now().strftime("%Y-%m-%d")

    parts = [
        f"<!-- Generated by Agentic Documentation Generator on {timestamp} -->",
        "",
    ]

    section_order = [
        "overview",
        "installation",
        "usage_guide",
        "api_docs",
        "architecture",
        "examples",
        "configuration",
        "contributing",
        "changelog",
    ]

    # Add sections in order
    for key in section_order:
        if key in sections and sections[key]:
            parts.append(sections[key])
            parts.append("")
            parts.append("---")
            parts.append("")

    # Add any extra sections not in the order list
    for key, content in sections.items():
        if key not in section_order and content:
            parts.append(content)
            parts.append("")

    parts.append(f"*Documentation generated on {timestamp}*")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# JSON output
# ---------------------------------------------------------------------------

def format_json(sections: Dict[str, str], analysis: Dict) -> str:
    """Format documentation as structured JSON."""
    output = {
        "metadata": {
            "project_name": analysis.get("project_name", "unknown"),
            "generated_at": datetime.now().isoformat(),
            "generator": "Agentic Documentation Generator",
            "language": analysis.get("language", "unknown"),
            "framework": analysis.get("framework", "unknown"),
            "architecture": analysis.get("architecture", "unknown"),
            "complexity": analysis.get("complexity", "unknown"),
            "total_files_analyzed": analysis.get("total_files", 0),
        },
        "analysis": {
            "description": analysis.get("description", ""),
            "features": analysis.get("features", []),
            "key_components": analysis.get("key_components", []),
            "dependencies": analysis.get("dependencies", []),
            "entry_points": analysis.get("entry_points", []),
        },
        "documentation": {
            key: content
            for key, content in sections.items()
            if content
        },
    }
    return json.dumps(output, indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# HTML output
# ---------------------------------------------------------------------------

def format_html(sections: Dict[str, str], analysis: Dict) -> str:
    """Generate a professional interactive HTML documentation page."""
    project_name = analysis.get("project_name", "Project Documentation")
    description = analysis.get("description", "")
    timestamp = datetime.now().strftime("%B %d, %Y")
    language = analysis.get("language", "")
    framework = analysis.get("framework", "")

    # Build sidebar nav
    nav_items = []
    section_order = [
        ("overview", "Overview"),
        ("installation", "Installation"),
        ("usage_guide", "Usage Guide"),
        ("api_docs", "API Reference"),
        ("architecture", "Architecture"),
        ("examples", "Examples"),
        ("configuration", "Configuration"),
        ("contributing", "Contributing"),
        ("changelog", "Changelog"),
    ]
    for key, label in section_order:
        if key in sections and sections[key]:
            nav_items.append(f'<li><a href="#{key}" class="nav-link">{label}</a></li>')

    nav_html = "\n".join(nav_items)

    # Build content sections
    content_parts = []
    for key, label in section_order:
        if key in sections and sections[key]:
            html_content = _markdown_to_html(sections[key])
            content_parts.append(f"""
        <section id="{key}" class="doc-section">
            <div class="section-content">
                {html_content}
            </div>
        </section>""")

    content_html = "\n".join(content_parts)

    # Badges
    badges = []
    if language:
        badges.append(f'<span class="badge badge-lang">{html_module.escape(language)}</span>')
    if framework and framework != "unknown":
        badges.append(f'<span class="badge badge-framework">{html_module.escape(framework)}</span>')
    badges_html = " ".join(badges)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html_module.escape(project_name)} — Documentation</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
    <style>
        :root {{
            --primary: #6366f1;
            --primary-dark: #4f46e5;
            --primary-light: #e0e7ff;
            --bg: #ffffff;
            --bg-secondary: #f8fafc;
            --sidebar-bg: #0f172a;
            --sidebar-text: #cbd5e1;
            --sidebar-hover: #1e293b;
            --sidebar-active: #6366f1;
            --text: #1e293b;
            --text-muted: #64748b;
            --border: #e2e8f0;
            --code-bg: #1e293b;
            --code-text: #e2e8f0;
            --inline-code-bg: #f1f5f9;
            --inline-code-text: #e11d48;
            --sidebar-width: 280px;
            --header-height: 60px;
        }}

        * {{ box-sizing: border-box; margin: 0; padding: 0; }}

        body {{
            font-family: 'Inter', sans-serif;
            background: var(--bg);
            color: var(--text);
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }}

        /* Top Header */
        .top-header {{
            height: var(--header-height);
            background: var(--sidebar-bg);
            display: flex;
            align-items: center;
            padding: 0 1.5rem;
            position: fixed;
            top: 0; left: 0; right: 0;
            z-index: 100;
            border-bottom: 1px solid #1e293b;
        }}
        .logo {{
            font-size: 1.1rem;
            font-weight: 700;
            color: #fff;
            letter-spacing: -0.02em;
        }}
        .logo span {{ color: var(--primary); }}
        .search-wrapper {{
            margin-left: auto;
            position: relative;
        }}
        #search-input {{
            background: #1e293b;
            border: 1px solid #334155;
            color: #fff;
            padding: 0.45rem 1rem 0.45rem 2.5rem;
            border-radius: 8px;
            font-size: 0.875rem;
            width: 260px;
            outline: none;
            transition: border-color 0.2s;
        }}
        #search-input:focus {{ border-color: var(--primary); }}
        #search-input::placeholder {{ color: #64748b; }}
        .search-icon {{
            position: absolute;
            left: 0.75rem;
            top: 50%;
            transform: translateY(-50%);
            color: #64748b;
            font-size: 0.875rem;
        }}
        .search-results {{
            position: absolute;
            top: calc(100% + 8px);
            right: 0;
            background: var(--sidebar-bg);
            border: 1px solid #334155;
            border-radius: 10px;
            width: 400px;
            max-height: 400px;
            overflow-y: auto;
            display: none;
            z-index: 200;
            box-shadow: 0 20px 40px rgba(0,0,0,0.4);
        }}
        .search-result-item {{
            padding: 0.75rem 1rem;
            border-bottom: 1px solid #1e293b;
            cursor: pointer;
            transition: background 0.15s;
        }}
        .search-result-item:hover {{ background: #1e293b; }}
        .search-result-item .result-title {{ color: #e2e8f0; font-size: 0.875rem; font-weight: 500; }}
        .search-result-item .result-preview {{ color: #64748b; font-size: 0.75rem; margin-top: 2px; }}

        /* Layout */
        .layout {{
            display: flex;
            margin-top: var(--header-height);
            min-height: calc(100vh - var(--header-height));
        }}

        /* Sidebar */
        .sidebar {{
            width: var(--sidebar-width);
            background: var(--sidebar-bg);
            position: fixed;
            top: var(--header-height);
            bottom: 0;
            left: 0;
            overflow-y: auto;
            padding: 1.5rem 0;
            border-right: 1px solid #1e293b;
        }}
        .sidebar-section {{
            padding: 0 1rem;
            margin-bottom: 1.5rem;
        }}
        .sidebar-section-title {{
            font-size: 0.7rem;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            color: #475569;
            padding: 0 0.5rem;
            margin-bottom: 0.5rem;
        }}
        .sidebar nav ul {{
            list-style: none;
        }}
        .nav-link {{
            display: block;
            padding: 0.5rem 0.75rem;
            color: var(--sidebar-text);
            text-decoration: none;
            border-radius: 6px;
            font-size: 0.875rem;
            transition: all 0.15s;
            margin-bottom: 2px;
        }}
        .nav-link:hover {{ background: var(--sidebar-hover); color: #fff; }}
        .nav-link.active {{ background: var(--primary); color: #fff; font-weight: 500; }}

        /* Main content */
        .main {{
            margin-left: var(--sidebar-width);
            flex: 1;
            min-width: 0;
        }}

        /* Hero */
        .hero {{
            background: linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%);
            padding: 4rem 3rem 3rem;
            border-bottom: 1px solid #1e293b;
        }}
        .hero h1 {{
            font-size: 2.5rem;
            font-weight: 800;
            color: #fff;
            letter-spacing: -0.04em;
            margin-bottom: 0.75rem;
        }}
        .hero p {{
            color: #94a3b8;
            font-size: 1.1rem;
            max-width: 600px;
            line-height: 1.6;
            margin-bottom: 1.25rem;
        }}
        .badges {{ display: flex; gap: 0.5rem; flex-wrap: wrap; }}
        .badge {{
            padding: 0.25rem 0.75rem;
            border-radius: 9999px;
            font-size: 0.75rem;
            font-weight: 600;
        }}
        .badge-lang {{ background: #312e81; color: #a5b4fc; }}
        .badge-framework {{ background: #1e3a5f; color: #7dd3fc; }}
        .meta-info {{
            margin-top: 1rem;
            color: #475569;
            font-size: 0.8rem;
        }}

        /* Content */
        .content {{
            max-width: 860px;
            padding: 3rem;
        }}

        .doc-section {{
            margin-bottom: 4rem;
            padding-bottom: 4rem;
            border-bottom: 1px solid var(--border);
        }}
        .doc-section:last-child {{ border-bottom: none; }}

        .section-content h1 {{
            font-size: 1.875rem; font-weight: 700; color: var(--text);
            margin-bottom: 1rem; letter-spacing: -0.03em;
        }}
        .section-content h2 {{
            font-size: 1.5rem; font-weight: 600; color: var(--text);
            margin: 2rem 0 1rem; padding-bottom: 0.5rem;
            border-bottom: 2px solid var(--primary-light);
        }}
        .section-content h3 {{
            font-size: 1.15rem; font-weight: 600; color: var(--text);
            margin: 1.5rem 0 0.75rem;
        }}
        .section-content h4 {{
            font-size: 1rem; font-weight: 600; color: var(--text-muted);
            margin: 1.25rem 0 0.5rem; text-transform: uppercase;
            letter-spacing: 0.05em; font-size: 0.8rem;
        }}
        .section-content p {{
            line-height: 1.75;
            color: #374151;
            margin-bottom: 1rem;
        }}
        .section-content ul, .section-content ol {{
            padding-left: 1.5rem;
            margin-bottom: 1rem;
        }}
        .section-content li {{
            line-height: 1.7;
            color: #374151;
            margin-bottom: 0.35rem;
        }}
        .section-content a {{
            color: var(--primary);
            text-decoration: none;
            border-bottom: 1px solid transparent;
        }}
        .section-content a:hover {{ border-bottom-color: var(--primary); }}

        /* Code blocks */
        .section-content pre {{
            background: var(--code-bg);
            border-radius: 10px;
            padding: 1.25rem 1.5rem;
            overflow-x: auto;
            margin: 1.25rem 0;
            position: relative;
            border: 1px solid #334155;
        }}
        .section-content pre code {{
            font-family: 'JetBrains Mono', monospace;
            font-size: 0.875rem;
            color: var(--code-text);
            line-height: 1.65;
            background: none;
            padding: 0;
            border-radius: 0;
            color: inherit;
        }}
        .copy-btn {{
            position: absolute;
            top: 0.75rem;
            right: 0.75rem;
            background: #334155;
            color: #94a3b8;
            border: none;
            padding: 0.25rem 0.6rem;
            border-radius: 5px;
            font-size: 0.7rem;
            cursor: pointer;
            transition: all 0.15s;
            font-family: 'Inter', sans-serif;
        }}
        .copy-btn:hover {{ background: var(--primary); color: #fff; }}

        .section-content code {{
            background: var(--inline-code-bg);
            color: var(--inline-code-text);
            padding: 0.15rem 0.4rem;
            border-radius: 4px;
            font-family: 'JetBrains Mono', monospace;
            font-size: 0.85em;
        }}

        /* Tables */
        .section-content table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1.25rem 0;
            font-size: 0.9rem;
        }}
        .section-content th {{
            background: var(--bg-secondary);
            padding: 0.75rem 1rem;
            text-align: left;
            font-weight: 600;
            font-size: 0.8rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: var(--text-muted);
            border-bottom: 2px solid var(--border);
        }}
        .section-content td {{
            padding: 0.75rem 1rem;
            border-bottom: 1px solid var(--border);
            color: #374151;
        }}
        .section-content tr:hover td {{ background: var(--bg-secondary); }}

        /* Blockquotes */
        .section-content blockquote {{
            border-left: 4px solid var(--primary);
            padding: 0.75rem 1.25rem;
            background: var(--primary-light);
            border-radius: 0 8px 8px 0;
            margin: 1.25rem 0;
            color: #3730a3;
        }}
        .section-content blockquote p {{ color: inherit; margin: 0; }}

        /* Collapsible details */
        .section-content details {{
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 0;
            margin: 1rem 0;
            overflow: hidden;
        }}
        .section-content summary {{
            padding: 0.75rem 1rem;
            cursor: pointer;
            font-weight: 500;
            background: var(--bg-secondary);
            user-select: none;
        }}
        .section-content details[open] summary {{
            border-bottom: 1px solid var(--border);
        }}
        .section-content details > *:not(summary) {{
            padding: 1rem;
        }}

        /* Syntax highlighting helpers */
        .hljs-keyword {{ color: #f472b6; }}
        .hljs-string {{ color: #86efac; }}
        .hljs-comment {{ color: #64748b; font-style: italic; }}
        .hljs-number {{ color: #fb923c; }}
        .hljs-function {{ color: #7dd3fc; }}
        .hljs-class {{ color: #a5b4fc; }}
        .hljs-built_in {{ color: #fbbf24; }}

        /* Scroll progress */
        .scroll-progress {{
            position: fixed;
            top: var(--header-height);
            left: 0;
            height: 3px;
            background: var(--primary);
            z-index: 99;
            transition: width 0.1s linear;
        }}

        /* Back to top */
        .back-to-top {{
            position: fixed;
            bottom: 2rem;
            right: 2rem;
            background: var(--primary);
            color: #fff;
            border: none;
            width: 42px;
            height: 42px;
            border-radius: 50%;
            cursor: pointer;
            font-size: 1.1rem;
            box-shadow: 0 4px 12px rgba(99,102,241,0.4);
            transition: all 0.2s;
            display: none;
            align-items: center;
            justify-content: center;
        }}
        .back-to-top:hover {{ transform: translateY(-2px); box-shadow: 0 6px 16px rgba(99,102,241,0.5); }}
        .back-to-top.visible {{ display: flex; }}

        /* Responsive */
        @media (max-width: 768px) {{
            .sidebar {{ display: none; }}
            .main {{ margin-left: 0; }}
            .content {{ padding: 1.5rem; }}
            .hero {{ padding: 2rem 1.5rem; }}
            .hero h1 {{ font-size: 1.75rem; }}
            #search-input {{ width: 180px; }}
        }}
    </style>
</head>
<body>
    <div class="scroll-progress" id="scroll-progress"></div>

    <header class="top-header">
        <div class="logo">⚡ <span>{html_module.escape(project_name)}</span> docs</div>
        <div class="search-wrapper">
            <span class="search-icon">🔍</span>
            <input type="text" id="search-input" placeholder="Search documentation..." autocomplete="off">
            <div class="search-results" id="search-results"></div>
        </div>
    </header>

    <div class="layout">
        <aside class="sidebar">
            <div class="sidebar-section">
                <div class="sidebar-section-title">Navigation</div>
                <nav>
                    <ul>
                        {nav_html}
                    </ul>
                </nav>
            </div>
        </aside>

        <main class="main">
            <div class="hero">
                <h1>{html_module.escape(project_name)}</h1>
                <p>{html_module.escape(description)}</p>
                <div class="badges">{badges_html}</div>
                <div class="meta-info">Generated on {timestamp} · Agentic Documentation Generator</div>
            </div>

            <div class="content">
                {content_html}
            </div>
        </main>
    </div>

    <button class="back-to-top" id="back-to-top" title="Back to top">↑</button>

    <script>
        // ── Search ──────────────────────────────────────────────────────────
        const searchInput = document.getElementById('search-input');
        const searchResults = document.getElementById('search-results');
        
        // Index all text content
        const searchIndex = [];
        document.querySelectorAll('.doc-section').forEach(section => {{
            const id = section.id;
            const headings = section.querySelectorAll('h1,h2,h3');
            headings.forEach(h => {{
                searchIndex.push({{
                    id,
                    title: h.textContent,
                    preview: h.nextElementSibling ? h.nextElementSibling.textContent.slice(0, 100) : '',
                }});
            }});
        }});

        searchInput.addEventListener('input', function() {{
            const q = this.value.toLowerCase().trim();
            if (!q) {{ searchResults.style.display = 'none'; return; }}
            const matches = searchIndex.filter(item =>
                item.title.toLowerCase().includes(q) || item.preview.toLowerCase().includes(q)
            ).slice(0, 8);
            if (matches.length === 0) {{ searchResults.style.display = 'none'; return; }}
            searchResults.innerHTML = matches.map(m => `
                <div class="search-result-item" onclick="goTo('${{m.id}}')">
                    <div class="result-title">${{m.title}}</div>
                    <div class="result-preview">${{m.preview}}</div>
                </div>
            `).join('');
            searchResults.style.display = 'block';
        }});

        document.addEventListener('click', e => {{
            if (!searchInput.contains(e.target) && !searchResults.contains(e.target)) {{
                searchResults.style.display = 'none';
            }}
        }});

        function goTo(id) {{
            const el = document.getElementById(id);
            if (el) {{ el.scrollIntoView({{ behavior: 'smooth', block: 'start' }}); }}
            searchResults.style.display = 'none';
            searchInput.value = '';
        }}

        // ── Active nav on scroll ─────────────────────────────────────────────
        const sections = document.querySelectorAll('.doc-section');
        const navLinks = document.querySelectorAll('.nav-link');
        const progress = document.getElementById('scroll-progress');
        const backToTop = document.getElementById('back-to-top');

        window.addEventListener('scroll', () => {{
            // Scroll progress bar
            const scrolled = (window.scrollY / (document.body.scrollHeight - window.innerHeight)) * 100;
            progress.style.width = scrolled + '%';

            // Active nav
            let current = '';
            sections.forEach(sec => {{
                if (window.scrollY >= sec.offsetTop - 120) current = sec.id;
            }});
            navLinks.forEach(link => {{
                link.classList.toggle('active', link.getAttribute('href') === '#' + current);
            }});

            // Back to top
            backToTop.classList.toggle('visible', window.scrollY > 400);
        }});

        backToTop.addEventListener('click', () => window.scrollTo({{ top: 0, behavior: 'smooth' }}));

        // ── Smooth nav scrolling ─────────────────────────────────────────────
        navLinks.forEach(link => {{
            link.addEventListener('click', e => {{
                e.preventDefault();
                const target = document.querySelector(link.getAttribute('href'));
                if (target) target.scrollIntoView({{ behavior: 'smooth', block: 'start' }});
            }});
        }});

        // ── Copy buttons on code blocks ──────────────────────────────────────
        document.querySelectorAll('pre').forEach(pre => {{
            const btn = document.createElement('button');
            btn.className = 'copy-btn';
            btn.textContent = 'copy';
            btn.addEventListener('click', () => {{
                navigator.clipboard.writeText(pre.querySelector('code').innerText).then(() => {{
                    btn.textContent = '✓ copied';
                    setTimeout(() => btn.textContent = 'copy', 2000);
                }});
            }});
            pre.style.position = 'relative';
            pre.appendChild(btn);
        }});

        // ── Basic syntax highlighting (keyword coloring) ──────────────────────
        document.querySelectorAll('pre code').forEach(block => {{
            let html = block.innerHTML;
            // Keywords
            const keywords = /\\b(def|class|import|from|return|if|else|elif|for|while|try|except|with|as|in|not|and|or|is|None|True|False|async|await|yield|pass|break|continue|raise|const|let|var|function|=>|export|default|interface|type|struct|fn|pub|mod|use|impl|trait|enum|match|self|super)\\b/g;
            html = html.replace(keywords, '<span class="hljs-keyword">$1</span>');
            // Strings
            html = html.replace(/(["'`])(?:(?!\1)[^\\]|\\.)*\1/g, '<span class="hljs-string">$&</span>');
            // Comments
            html = html.replace(/(#[^\n]*|\/\/[^\n]*)/g, '<span class="hljs-comment">$1</span>');
            // Numbers
            html = html.replace(/\\b(\\d+\\.?\\d*)\\b/g, '<span class="hljs-number">$1</span>');
            block.innerHTML = html;
        }});
    </script>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Markdown → HTML conversion (simple, no deps)
# ---------------------------------------------------------------------------

def _markdown_to_html(md: str) -> str:
    """Convert Markdown to HTML for embedding in the doc page."""
    import re

    # Remove the generated comment if present
    md = re.sub(r"<!--.*?-->", "", md, flags=re.DOTALL)

    lines = md.split("\n")
    output = []
    i = 0
    in_code_block = False
    code_lang = ""
    code_lines = []

    while i < len(lines):
        line = lines[i]

        # Code block start/end
        if line.startswith("```"):
            if in_code_block:
                code_content = html_module.escape("\n".join(code_lines))
                output.append(f'<pre><code class="language-{code_lang}">{code_content}</code></pre>')
                in_code_block = False
                code_lines = []
                code_lang = ""
            else:
                in_code_block = True
                code_lang = line[3:].strip() or "text"
            i += 1
            continue

        if in_code_block:
            code_lines.append(line)
            i += 1
            continue

        # Headings
        if line.startswith("# "):
            output.append(f"<h1>{_inline(line[2:])}</h1>")
        elif line.startswith("## "):
            output.append(f"<h2>{_inline(line[3:])}</h2>")
        elif line.startswith("### "):
            output.append(f"<h3>{_inline(line[4:])}</h3>")
        elif line.startswith("#### "):
            output.append(f"<h4>{_inline(line[5:])}</h4>")
        # Horizontal rule
        elif re.match(r"^---+$|^\*\*\*+$", line.strip()):
            output.append("<hr>")
        # Blockquote
        elif line.startswith("> "):
            output.append(f"<blockquote><p>{_inline(line[2:])}</p></blockquote>")
        # Unordered list
        elif re.match(r"^[-*+] ", line):
            items = []
            while i < len(lines) and re.match(r"^[-*+] ", lines[i]):
                items.append(f"<li>{_inline(lines[i][2:])}</li>")
                i += 1
            output.append("<ul>" + "".join(items) + "</ul>")
            continue
        # Ordered list
        elif re.match(r"^\d+\. ", line):
            items = []
            while i < len(lines) and re.match(r"^\d+\. ", lines[i]):
                clean_line = re.sub(r'^\d+\. ', '', lines[i])
                items.append(f"<li>{_inline(clean_line)}</li>")
                i += 1
            output.append("<ol>" + "".join(items) + "</ol>")
            continue
        # Table
        elif "|" in line and i + 1 < len(lines) and re.match(r"^\|?[-| :]+\|?$", lines[i + 1].strip()):
            headers = [h.strip() for h in line.strip("|").split("|")]
            i += 2  # Skip separator
            rows = []
            while i < len(lines) and "|" in lines[i]:
                cells = [c.strip() for c in lines[i].strip("|").split("|")]
                rows.append(cells)
                i += 1
            thead = "<tr>" + "".join(f"<th>{_inline(h)}</th>" for h in headers) + "</tr>"
            tbody = "".join(
                "<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in row) + "</tr>"
                for row in rows
            )
            output.append(f"<table><thead>{thead}</thead><tbody>{tbody}</tbody></table>")
            continue
        # Empty line
        elif line.strip() == "":
            output.append("")
        # Paragraph
        else:
            # Collect paragraph lines
            para_lines = []
            while i < len(lines) and lines[i].strip() and not lines[i].startswith(("#", ">", "-", "*", "+", "```", "---", "***")):
                if re.match(r"^\d+\. ", lines[i]):
                    break
                if "|" in lines[i]:
                    break
                para_lines.append(lines[i])
                i += 1
            if para_lines:
                output.append(f"<p>{_inline(' '.join(para_lines))}</p>")
            continue

        i += 1

    # Handle unclosed code block
    if in_code_block and code_lines:
        code_content = html_module.escape("\n".join(code_lines))
        output.append(f'<pre><code class="language-{code_lang}">{code_content}</code></pre>')

    return "\n".join(output)


def _inline(text: str) -> str:
    """Process inline Markdown: bold, italic, code, links."""
    import re

    text = html_module.escape(text)
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"__(.+?)__", r"<strong>\1</strong>", text)
    # Italic
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    text = re.sub(r"_(.+?)_", r"<em>\1</em>", text)
    # Inline code
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    # Links
    text = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', text)
    return text